// lib/data.js
// Complete menu database for الخلاط (The Mixer) - Sohag

export const RESTAURANT_INFO = {
  name: "الخلاط",
  tagline: "The Mixer • Sohag",
  description: "أصل الانبساط.. عصير فريش وخلطات ملهاش مثيل في سوهاج",
  address: "سوهاج — بجوار مستشفى الهلال",
  phone: "01007375151",
  whatsapp: "201007375151",
  hours: "يومياً من ١٢:٠٠ ظهراً حتى ٠٢:٠٠ بعد منتصف الليل",
};

export const MENU_CATEGORIES = [
  { id: "all", name: "الكل " },
  { id: "special", name: "سبيشيال الخلاط " },
  { id: "winter", name: "الركن الشتوي " },
  { id: "waffles", name: "وافلز الخلاط " },
  { id: "rice-pudding", name: "أرز بلبن " },
  { id: "juices-1l", name: "منيو الـ 1 لتر " },
  { id: "sobia-ramadan", name: "سوبيا ورمضانيات " },
  { id: "add-ons", name: "إضافات " },
];

export const MENU_ITEMS = [
  // ================= SPECIAL MIXES =================
  {
    id: "shikar",
    name: "شيكار",
    category: "special",
    price: 65,
    badge: "الأكثر طلباً ",
    img: "/products/p1.jpg",
    desc: "خلطة الخلاط السحرية الغنية بقطع الفواكه والكريمة.",
  },
  {
    id: "lacasa",
    name: "لاكاسا",
    category: "special",
    price: 65,
    badge: "مميز ",
    img: "/products/p2.jpg",
    desc: "كوكتيل طبقات غني بالفواكه الطازجة والآيس كريم.",
  },
  {
    id: "avocado-nuts",
    name: "أفوكادو عصير مكسرات",
    category: "special",
    price: 85,
    badge: "فاخر ",
    img: "/products/p3.jpg",
    desc: "أفوكادو بلدي طازج مع العسل الطبيعي والمكسرات الفاخرة.",
  },
  {
    id: "manjawy",
    name: "مانجاوي",
    category: "special",
    price: 60,
    badge: "انتعاش ",
    img: "/products/p4.jpg",
    desc: "عصير مانجو مركز غني بقطع المانجو الطبيعية.",
  },
  {
    id: "fustokado-pro",
    name: "فستوكادو برو",
    category: "special",
    price: 65,
    badge: "جديد ✨",
    img: "/products/p5.jpg",
    desc: "مزيج الأفوكادو والفستق الحلبي مع صوص الكريمة.",
  },
  {
    id: "soft-caramel",
    name: "سوفت كراميل",
    category: "special",
    price: 65,
    img: "/products/p6.jpg",
    desc: "ميلك شيك كراميل غني مع صوص الكراميل الدافي.",
  },
  {
    id: "soft-oreo",
    name: "سوفت أوريو",
    category: "special",
    price: 65,
    badge: "محبوب الشباب ",
    img: "/products/p2.jpg",
    desc: "أوريو مع الآيس كريم وبسكويت مقرمش غرقان شوكولاتة.",
  },
  {
    id: "romanisto",
    name: "رومانستو",
    category: "special",
    price: 55,
    img: "/products/p3.jpg",
    desc: "مزيج الرمان المنعش مع النعناع والصودا الفوارة.",
  },
  {
    id: "mawg",
    name: "مووج",
    category: "special",
    price: 65,
    img: "/products/p4.jpg",
    desc: "خلطة منعشة من التوت والفواكه الاستوائية.",
  },
  {
    id: "electric-lime",
    name: "إلكتريك لايم",
    category: "special",
    price: 55,
    img: "/products/p5.jpg",
    desc: "ليمون أخضر مثلج مع صودا فوارة ونكهة طازجة.",
  },
  {
    id: "classic-mojito",
    name: "كلاسيك موخيتو",
    category: "special",
    price: 55,
    badge: "بارد ",
    img: "/products/p1.jpg",
    desc: "ليمون ونعناع مع صودا ومكعبات ثلج لانتعاش فوري.",
  },
  {
    id: "nairobi",
    name: "نيروبي",
    category: "special",
    price: 65,
    img: "/products/p6.jpg",
    desc: "ميكس استوائي فريد من عصائر الخلاط.",
  },
  {
    id: "tropical",
    name: "تروبيكال",
    category: "special",
    price: 65,
    img: "/products/p4.jpg",
    desc: "فواكه استوائية مشكلة تعزز مودك في أي وقت.",
  },
  {
    id: "paradise",
    name: "بارادايس",
    category: "special",
    price: 65,
    img: "/products/p2.jpg",
    desc: "كوكتيل طبقات غني بالطعم اللذيذ.",
  },
  {
    id: "fruit-salad-icecream",
    name: "سلطة فواكه آيس كريم",
    category: "special",
    price: 60,
    badge: "لذيذ ",
    img: "/products/p6.jpg",
    desc: "قطع فواكه موسميّة غارقة في الآيس كريم اللذيذ.",
  },
  {
    id: "fruit-salad-box",
    name: "علبة سلطة فواكه",
    category: "special",
    price: 60,
    img: "/products/p1.jpg",
    desc: "علبة فواكه طازجة مشكلة ومقطعة بعناية.",
  },
  {
    id: "havana",
    name: "هافانا",
    category: "special",
    price: 80,
    img: "/products/p3.jpg",
    desc: "كوكتيل هافانا الراقِ بقطع الفاكهة والعسل.",
  },
  {
    id: "florida",
    name: "فلوريدا",
    category: "special",
    price: 65,
    img: "/products/p5.jpg",
    desc: "مزيج فلوريدا الفريش من العصائر الطبيعية.",
  },
  {
    id: "mirage",
    name: "ميراج",
    category: "special",
    price: 65,
    img: "/products/p4.jpg",
    desc: "خلطة ميراج الخاصة بالخلاط.",
  },

  // ================= WINTER CORNER (الركن الشتوي) =================
  {
    id: "balila-plain",
    name: "بليلة سادة",
    category: "winter",
    price: 35,
    img: "/products/p1.jpg",
    desc: "بليلة سخنة بالحليب الطبيعي والسكر.",
  },
  {
    id: "balila-nuts",
    name: "بليلة مكسرات",
    category: "winter",
    price: 75,
    badge: "دافئ ",
    img: "/products/p2.jpg",
    desc: "بليلة بالحليب غنية بالمكسرات المحمصة القشطة.",
  },
  {
    id: "balila-chickpeas",
    name: "بليلة حمص",
    category: "winter",
    price: 30,
    img: "/products/p3.jpg",
    desc: "حمص الشام الدافي الخفيف والمنعش.",
  },
  {
    id: "kuskusi-plain",
    name: "كسكسي سادة",
    category: "winter",
    price: 40,
    img: "/products/p4.jpg",
    desc: "كسكسي مصري سخن بالسكر والسمن البلدي.",
  },
  {
    id: "kuskusi-nuts",
    name: "كسكسي مكسرات",
    category: "winter",
    price: 70,
    img: "/products/p5.jpg",
    desc: "كسكسي بالسمن البلدي والسكر والمكسرات المشكلة.",
  },
  {
    id: "sahlab-plain",
    name: "سحلب سادة",
    category: "winter",
    price: 35,
    img: "/products/p6.jpg",
    desc: "سحلب دافئ تقيل مع سمسم ومكسرات خفيفة.",
  },
  {
    id: "sahlab-fruits",
    name: "سحلب فواكه",
    category: "winter",
    price: 60,
    img: "/products/p1.jpg",
    desc: "سحلب سخن مغطى بقطع الفواكه الطازجة.",
  },
  {
    id: "sahlab-oreo",
    name: "سحلب أوريو",
    category: "winter",
    price: 60,
    img: "/products/p2.jpg",
    desc: "سحلب بالحليب وبسكويت الأوريو المطحون.",
  },
  {
    id: "sahlab-lotus",
    name: "سحلب لوتس",
    category: "winter",
    price: 55,
    img: "/products/p3.jpg",
    desc: "سحلب سخن غرقان بزبوت وزبدة اللوتس الشهية.",
  },
  {
    id: "sahlab-pistachio",
    name: "سحلب بستاشيو",
    category: "winter",
    price: 60,
    badge: "مميز ",
    img: "/products/p4.jpg",
    desc: "سحلب بصوص وزبدة الفستق الحلبي.",
  },
  {
    id: "sahlab-nuts",
    name: "سحلب مكسرات",
    category: "winter",
    price: 65,
    img: "/products/p5.jpg",
    desc: "سحلب غني بتشكيلة مكسرات محمصة.",
  },
  {
    id: "om-ali-plain",
    name: "أم علي سادة",
    category: "winter",
    price: 45,
    img: "/products/p6.jpg",
    desc: "طاجن أم علي بالحليب الساخن والقشطة.",
  },
  {
    id: "om-ali-nuts",
    name: "أم علي مكسرات",
    category: "winter",
    price: 85,
    badge: "الأكثر طلب شتاءً ",
    img: "/products/p1.jpg",
    desc: "طاجن أم علي سخن بالفرن محشو بالمكسرات الفاخرة والقشطة.",
  },
  {
    id: "om-ali-pistachio",
    name: "أم علي بستاشيو",
    category: "winter",
    price: 70,
    img: "/products/p2.jpg",
    desc: "طاجن أم علي مع زبدة الفستق والمكسرات.",
  },
  {
    id: "om-ali-nutella",
    name: "أم علي نوتيلا",
    category: "winter",
    price: 60,
    img: "/products/p3.jpg",
    desc: "طاجن أم علي سخن غرقان شوكولاتة نوتيلا.",
  },
  {
    id: "om-ali-lotus",
    name: "أم علي لوتس",
    category: "winter",
    price: 60,
    img: "/products/p4.jpg",
    desc: "طاجن أم علي بزبادي وبسكويت اللوتس.",
  },

  // ================= WAFFLES (وافلز الخلاط) =================
  {
    id: "waffle-nutella-fruits",
    name: "وافلز نوتيلا فواكه",
    category: "waffles",
    price: 70,
    badge: "مكس رهيب ",
    img: "/products/p5.jpg",
    desc: "وافلز بلجيكي مقرمش غرقان نوتيلا وقطع فواكه طازجة.",
  },
  {
    id: "waffle-nutella-icecream",
    name: "وافلز نوتيلا آيس كريم",
    category: "waffles",
    price: 60,
    img: "/products/p6.jpg",
    desc: "وافل سخن مع بول آيس كريم وصوص شوكولاتة نوتيلا.",
  },
  {
    id: "waffle-nutella-plain",
    name: "وافلز نوتيلا سادة",
    category: "waffles",
    price: 40,
    img: "/products/p1.jpg",
    desc: "وافلز الذهبي المقرمش مغطى بصوص النوتيلا الأصلي.",
  },
  {
    id: "waffle-pistachio",
    name: "وافلز بستاشيو",
    category: "waffles",
    price: 70,
    badge: "فاخر ",
    img: "/products/p2.jpg",
    desc: "وافلز مقرمش مع زبدة الفستق والمكسرات.",
  },
  {
    id: "waffle-nutella-lotus",
    name: "وافلز نوتيلا لوتس",
    category: "waffles",
    price: 50,
    img: "/products/p3.jpg",
    desc: "مكس وافل نوتيلا مع زبدة وبسكويت اللوتس.",
  },
  {
    id: "waffle-mix-couple",
    name: "وافلز ميكس كابل",
    category: "waffles",
    price: 45,
    img: "/products/p4.jpg",
    desc: "وافلز مقسم إلى نكهتين مفضلتين حسب اختيارك.",
  },
  {
    id: "waffle-elmixer",
    name: "وافلز الخلاط الملكي",
    category: "waffles",
    price: 100,
    badge: "الملكي ",
    img: "/products/p5.jpg",
    desc: "وافلز عملاق بطبقات الفواكه والآيس كريم والنوتيلا والمكسرات واللوتس.",
  },

  // ================= RICE PUDDING (أرز بلبن) =================
  {
    id: "rice-pudding-plain",
    name: "أرز بلبن سادة",
    category: "rice-pudding",
    price: 30,
    img: "/products/p6.jpg",
    desc: "أرز بلبن كريمي طازج بالحليب الصافي.",
  },
  {
    id: "rice-pudding-icecream",
    name: "أرز بلبن آيس كريم",
    category: "rice-pudding",
    price: 50,
    img: "/products/p1.jpg",
    desc: "أرز بلبن مثلج مغطى ببولة آيس كريم فانيليا وصوص.",
  },
  {
    id: "rice-pudding-nuts",
    name: "أرز بلبن مكسرات",
    category: "rice-pudding",
    price: 55,
    img: "/products/p2.jpg",
    desc: "أرز بلبن غني بالمكسرات المحمصة والزبيب والسوداني.",
  },
  {
    id: "rice-pudding-fruits",
    name: "أرز بلبن فواكه",
    category: "rice-pudding",
    price: 50,
    img: "/products/p3.jpg",
    desc: "أرز بلبن كريمي مع تشكيلة قطع فواكه موسمية.",
  },
  {
    id: "rice-pudding-cashew",
    name: "أرز بلبن كاجو",
    category: "rice-pudding",
    price: 60,
    badge: "فاخر ",
    img: "/products/p4.jpg",
    desc: "أرز بلبن مقرمش بقطع الكاجو المحمص والHoney.",
  },
  {
    id: "rice-pudding-lotus",
    name: "أرز بلبن لوتس",
    category: "rice-pudding",
    price: 50,
    img: "/products/p5.jpg",
    desc: "أرز بلبن بزبدة وبسكويت اللوتس البلجيكي.",
  },
  {
    id: "rice-pudding-mango",
    name: "أرز بلبن قطع مانجا",
    category: "rice-pudding",
    price: 50,
    badge: "مفضل الصيف ",
    img: "/products/p6.jpg",
    desc: "أرز بلبن غرقان بقطع المانجو الفريش وصوص المانجو.",
  },
  {
    id: "rice-pudding-special",
    name: "أرز بلبن سبيشيال الخلاط",
    category: "rice-pudding",
    price: 75,
    badge: "سبيشيال ",
    img: "/products/p1.jpg",
    desc: "بول أرز بلبن كبير مع آيس كريم وفواكه ومكسرات وقشطة وعسل.",
  },

  // ================= 1 LITER JUICES (منيو 1 لتر) =================
  {
    id: "1l-mango",
    name: "مانجو (1 لتر)",
    category: "juices-1l",
    price: 95,
    badge: "1 لتر ",
    img: "/products/p4.jpg",
    desc: "زجاجة مانجو طبيعي مركز 100% سعة 1 لتر.",
  },
  {
    id: "1l-guava",
    name: "جوافة (1 لتر)",
    category: "juices-1l",
    price: 90,
    img: "/products/p3.jpg",
    desc: "عصير جوافة بالحليب فريش 1 لتر.",
  },
  {
    id: "1l-strawberry",
    name: "فراولة (1 لتر)",
    category: "juices-1l",
    price: 90,
    img: "/products/p1.jpg",
    desc: "عصير فراولة طبيعي مثلج سعة 1 لتر.",
  },
  {
    id: "1l-banana",
    name: "موز بالحليب (1 لتر)",
    category: "juices-1l",
    price: 90,
    img: "/products/p2.jpg",
    desc: "موز بالحليب الفريش سعة 1 لتر.",
  },
  {
    id: "1l-cantaloupe",
    name: "كنتالوب (1 لتر)",
    category: "juices-1l",
    price: 90,
    img: "/products/p5.jpg",
    desc: "عصير كنتالوب فريش 1 لتر.",
  },
  {
    id: "1l-lemon",
    name: "ليمون فريش (1 لتر)",
    category: "juices-1l",
    price: 90,
    img: "/products/p3.jpg",
    desc: "عصير ليمون منعش سعة 1 لتر.",
  },
  {
    id: "1l-orange",
    name: "برتقال فريش (1 لتر)",
    category: "juices-1l",
    price: 90,
    img: "/products/p4.jpg",
    desc: "برتقال طبيعي معصور طازج 1 لتر.",
  },
  {
    id: "1l-apple-elmixer",
    name: "تفاح الخلاط (1 لتر)",
    category: "juices-1l",
    price: 90,
    img: "/products/p6.jpg",
    desc: "عصير تفاح الخلاط الطبيعي 1 لتر.",
  },
  {
    id: "1l-kiwi",
    name: "كيوي (1 لتر)",
    category: "juices-1l",
    price: 180,
    badge: "فيتامين C ",
    img: "/products/p5.jpg",
    desc: "عصير كيوي طبيعي مركز 1 لتر.",
  },
  {
    id: "1l-pineapple",
    name: "أناناس (1 لتر)",
    category: "juices-1l",
    price: 190,
    img: "/products/p2.jpg",
    desc: "عصير أناناس فريش 1 لتر.",
  },
  {
    id: "1l-mango-avocado",
    name: "مانجو + أفوكادو (1 لتر)",
    category: "juices-1l",
    price: 150,
    badge: "مكس الطاقة ",
    img: "/products/p3.jpg",
    desc: "مزيج قوام الأفوكادو وطعم المانجو الفريش 1 لتر.",
  },
  {
    id: "1l-avocado-banana",
    name: "أفوكادو + موز (1 لتر)",
    category: "juices-1l",
    price: 150,
    img: "/products/p4.jpg",
    desc: "خلطة أفوكادو بالموز والعسل سعة 1 لتر.",
  },
  {
    id: "1l-peach-mango",
    name: "خوخ + مانجو (1 لتر)",
    category: "juices-1l",
    price: 150,
    img: "/products/p1.jpg",
    desc: "مكس خوخ ومانجو استوائي 1 لتر.",
  },
  {
    id: "1l-avocado-strawberry",
    name: "أفوكادو + فراولة (1 لتر)",
    category: "juices-1l",
    price: 150,
    img: "/products/p2.jpg",
    desc: "أفوكادو غني مع فراولة طبيعية 1 لتر.",
  },
  {
    id: "1l-pineapple-kiwi",
    name: "أناناس + كيوي (1 لتر)",
    category: "juices-1l",
    price: 170,
    img: "/products/p5.jpg",
    desc: "مكس أناناس وكيوي حامض حلو منظم للمود 1 لتر.",
  },

  // ================= SOBIA & RAMADAN (سوبيا ورمضانيات) =================
  {
    id: "sobia-plain",
    name: "سوبيا سادة",
    category: "sobia-ramadan",
    price: 30,
    img: "/products/p1.jpg",
    desc: "سوبيا الخلاط الشهيرة باردة ومنعشة.",
  },
  {
    id: "sobia-mango",
    name: "سوبيا مانجو",
    category: "sobia-ramadan",
    price: 45,
    badge: "الأكثر شعبية ",
    img: "/products/p4.jpg",
    desc: "سوبيا كريمية مع عصير وقطع المانجو.",
  },
  {
    id: "sobia-strawberry",
    name: "سوبيا فراولة",
    category: "sobia-ramadan",
    price: 45,
    img: "/products/p1.jpg",
    desc: "سوبيا الخلاط مع نكهة الفراولة الفريش.",
  },
  {
    id: "sobia-berry",
    name: "سوبيا توت",
    category: "sobia-ramadan",
    price: 50,
    img: "/products/p5.jpg",
    desc: "سوبيا منعشة بصوص التوت المشكل.",
  },
  {
    id: "sobia-lotus",
    name: "سوبيا لوتس",
    category: "sobia-ramadan",
    price: 50,
    img: "/products/p3.jpg",
    desc: "سوبيا بصوص اللوتس وبسكويت لوتس مطحون.",
  },
  {
    id: "sobia-pistachio",
    name: "سوبيا بستاشيو",
    category: "sobia-ramadan",
    price: 50,
    badge: "مميز ",
    img: "/products/p2.jpg",
    desc: "سوبيا باردة غنية بزبادي وبستاشيو.",
  },
  {
    id: "tamarind",
    name: "تمر هندي بلدنا",
    category: "sobia-ramadan",
    price: 30,
    img: "/products/p6.jpg",
    desc: "تمر هندي طبيعي مثلج ومضبوط.",
  },
  {
    id: "doum-milk",
    name: "دوم بالحليب",
    category: "sobia-ramadan",
    price: 30,
    img: "/products/p2.jpg",
    desc: "عصير دوم طبيعي مغذي بالحليب الطازج.",
  },
  {
    id: "dates-milk",
    name: "بلح بالحليب",
    category: "sobia-ramadan",
    price: 45,
    img: "/products/p3.jpg",
    desc: "بلح أسواني فاخر منقوع في الحليب الدافئ أو البارد.",
  },
  {
    id: "peanuts-milk",
    name: "سوداني بالحليب",
    category: "sobia-ramadan",
    price: 45,
    img: "/products/p4.jpg",
    desc: "مزيج زبدة السوداني والحليب الغني للطاقة.",
  },
  {
    id: "karkadeh",
    name: "كركديه عسلي مثلج",
    category: "sobia-ramadan",
    price: 30,
    img: "/products/p1.jpg",
    desc: "كركديه أسواني مثلج محلى بالعسل.",
  },
  {
    id: "kharroub",
    name: "خروب طبيعي",
    category: "sobia-ramadan",
    price: 30,
    img: "/products/p5.jpg",
    desc: "عصير خروب مصري مركز وبارد.",
  },
  {
    id: "cocktail-elmixer",
    name: "عصير كوكتيل الخلاط الرمضاني",
    category: "sobia-ramadan",
    price: 60,
    badge: "كوكتيل رمضاني ",
    img: "/products/p6.jpg",
    desc: "خلطة العصائر الرمضانية الخاصة بالخلاط.",
  },

  // ================= ADD-ONS (إضافات) =================
  {
    id: "addon-honey",
    name: "إضافة عسل طبيعي",
    category: "add-ons",
    price: 7,
    img: "/products/p1.jpg",
    desc: "عسل نقي 100% لإضافة حلاوة طبيعية.",
  },
  {
    id: "addon-nutella",
    name: "إضافة صوص نوتيلا",
    category: "add-ons",
    price: 10,
    img: "/products/p2.jpg",
    desc: "بول شوكولاتة نوتيلا غنية.",
  },
  {
    id: "addon-nuts",
    name: "إضافة مكسرات مشكلة",
    category: "add-ons",
    price: 20,
    img: "/products/p3.jpg",
    desc: "تشكيلة كاجو، فستق، وبندق محمصة.",
  },
  {
    id: "addon-cream",
    name: "إضافة قشطة بلدي",
    category: "add-ons",
    price: 7,
    img: "/products/p4.jpg",
    desc: "قشطة بلدي دسمة وغنية.",
  },
  {
    id: "addon-basbousa-kunafa",
    name: "قطعة بسبوسة أو كنافة",
    category: "add-ons",
    price: 5,
    img: "/products/p5.jpg",
    desc: "قطعة حلويات شرقية طازجة تضاف لطبقك.",
  },
];
